### ISSUE TITLE
オークション入札時にランタイムエラーが発生

### ISSUE THREAD

**Issue by maruhiko** [KyuzanInc/mint-sdk-js#81]
入札して取引が終わると元のページに戻らずにエラーが発生
入札自体は正常に行われている

![スクリーンショット 2021-11-08 18 27 47](https://user-images.githubusercontent.com/30888315/140717158-50cdbdf1-115c-41cb-afa0-d961de421665.png)

**Comment by tomonari-t** [comment]
exampleに移ったので閉じる
