### ISSUE TITLE
最低入札価格の桁数増えると表示が崩れる

### ISSUE THREAD

**Issue by maruhiko** [KyuzanInc/mint-sdk-js#82]
ボタンの表記が本来は「xxx ETH以上で入札」と表記されるが、xxxの桁数が増えると表記が崩れる

![スクリーンショット 2021-11-08 18 39 45](https://user-images.githubusercontent.com/30888315/140718887-9b339686-ceef-4c02-9470-50a20d075428.png)

**Comment by tomonari-t** [comment]
exampleに移ったので閉じる
